//
export const images = {
    BACK_BUTTON: require("../assets/pictures/100% Copy.png"),
    BACKGROUND: require("../assets/pictures/backGr.png"),
    BOTTOM: require("../assets/pictures/bottomPic.jpg"),
    HIT: require("../assets/pictures/хит.png"),
    ICON_BACK_CLICK: require("../assets/pictures/icon_back_click.png"),
    ICON_FACEBOOK: require("../assets/pictures/icon_facebook.png"),
    ICON_HEART_ACTIVE: require("../assets/pictures/icon_heart_active.png"),
    ICON_HEART_GRAY: require("../assets/pictures/icon_heart_gray.png"),
    ICON_LOCATING: require("../assets/pictures/icon_locating.png"),
    ICON_MAP_LIST: require("../assets/pictures/icon_map_list.png"),
    ICON_PENCIL_EDIT: require("../assets/pictures/icon_pencil_edit.png"),
    ICON_PLUS: require("../assets/pictures/icon_plus.png"),
    ICON_PRESSURE: require("../assets/pictures/icon_pressure.png"),
    ICON_READ_MORE_CLICK: require("../assets/pictures/icon_read_more_click.png"),
    ICON_READ_MORE: require("../assets/pictures/icon_read_more.png"),
    ICON_RUBLE: require("../assets/pictures/icon_ruble.png"),
    ICON_SEARCH_CLICK: require("../assets/pictures/icon_search_click.png"),
    ICON_SEARCH: require("../assets/pictures/icon_search.png"),
    ICON_SENT_CLICK: require("../assets/pictures/icon_sent_click.png"),
    ICON_SENT: require("../assets/pictures/icon_sent.png"),
    ICON_SWITCH_PIN_ACTIVE: require("../assets/pictures/icon_swich_pin_active.png"),
    ICON_SWITCH_FAVORITE: require("../assets/pictures/icon_switch_favorit.png"),
    IMAGE_NO_COFFE: require("../assets/pictures/image_no_coffe.png"),
    LIST: require("../assets/pictures/карта-список.png"),
    OFF_SWITCH: require("../assets/pictures/Off Switch.png"),
    OVAL_4: require("../assets/pictures/Oval 4.png"),
    OVAL_5: require("../assets/pictures/Oval 5.png"),
    SIMVOL_RUB: require("../assets/pictures/simvol_rub.png"),
    SlICE: require("../assets/pictures/Slice.png"),
    SPLASH_ANIMATION: require("../assets/pictures/18342-coffee.json"),
    USER: require("../assets/pictures/user_borders.png"),
};